-- Seed plans only (generated from src/shared/data/exercises.ts)
begin;

-- Remove existing base template plans and their exercises
delete from plan_exercises where plan_id in (select id from workout_plans where is_template = true);
delete from workout_plans where is_template = true;

with ex as (select id, name from exercises)
insert into workout_plans (user_id, name, description, type, days_per_week, estimated_duration_min, is_template, is_public) values
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Full Body (Iniciante)', 'Sessão completa para iniciantes, foco em técnica e compostos básicos.', 'full_body', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Full Body (Intermédio)', 'Treino completo com mais volume e compostos.', 'full_body', 3, 70, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Push (Peito/Tríceps)', 'Peito e tríceps com foco em força e hipertrofia.', 'chest_triceps', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Pull (Costas/Bíceps)', 'Costas e bíceps com remadas e puxadas.', 'back_biceps', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Legs (Quadríceps)', 'Foco em quadríceps e agachamentos.', 'legs_quad', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Posterior & Glúteos', 'Femorais e glúteos com hinge pesado.', 'legs_posterior', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Upper (Intermédio)', 'Treino de trem superior equilibrado.', 'upper', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Lower (Intermédio)', 'Treino de trem inferior equilibrado.', 'lower', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'PPL - Push', 'Push day clássico para PPL.', 'push', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'PPL - Pull', 'Pull day clássico para PPL.', 'pull', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'PPL - Legs', 'Leg day clássico para PPL.', 'legs_quad', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Strength 5x5', 'Plano base de força com 5x5 nos principais levantamentos.', 'full_body', 3, 70, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Hipertrofia Upper', 'Volume extra para membros superiores.', 'upper', 4, 70, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Condicionamento HIIT', 'Sessão rápida de cardio intenso.', 'cardio_hiit', 2, 30, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Core & Mobility', 'Core, estabilidade e mobilidade.', 'core', 2, 35, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Glúteos Intensivo', 'Foco em glúteos e posterior.', 'legs_posterior', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Panturrilhas & Core', 'Panturrilha + core para estabilidade.', 'core', 2, 35, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Power Upper', 'Força e potência no trem superior.', 'upper', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Athletic Performance', 'Potência, core e condicionamento geral.', 'full_body', 3, 60, true, true) returning id, name;

-- Link exercises to templates
with p as (select id, name from workout_plans where is_template = true), ex as (select id, name from exercises)
insert into plan_exercises (plan_id, exercise_id, order_index, sets, reps_min, reps_max, rest_seconds) values
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Agachamento com Halter'),0, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Supino com Halteres'),1, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),2, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Linha com Halteres'),3, 3, 10, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Desenvolvimento de Ombro'),4, 2, 10, 12, 60),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Prancha (Plank)'),5, 3, 30, 45, 45),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Supino (Barbell)'),1, 4, 6, 8, 120),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),2, 4, 6, 8, 120),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Press Militar (Military Press)'),3, 3, 8, 10, 90),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),4, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Pallof Press'),5, 3, 12, 15, 45),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 6, 8, 120),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino Inclinado'),1, 3, 8, 10, 90),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino Inclinado com Halteres'),2, 3, 8, 12, 90),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Crossover no Cabo'),3, 3, 10, 12, 60),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Push Down com Corda'),4, 3, 10, 12, 60),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino com Grip Fechado'),5, 3, 6, 8, 90),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),0, 4, 6, 8, 120),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Puxada Neutra'),1, 3, 8, 12, 90),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Remada T-Bar'),2, 3, 8, 12, 90),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Face Pull'),3, 3, 12, 15, 60),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Rosca EZ'),4, 3, 8, 12, 60),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Rosca Martelo'),5, 3, 10, 12, 60),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Belt Squat'),1, 4, 8, 12, 120),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Leg Press'),2, 3, 8, 12, 90),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Agachamento Búlgaro'),3, 3, 8, 10, 90),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Extensão de Perna'),4, 3, 10, 12, 60),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Elevação de Gémeos em Pé'),5, 4, 10, 15, 45),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Levantamento Morto Romeno'),0, 4, 6, 8, 120),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Hip Thrust'),1, 4, 8, 10, 90),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Flexão de Perna'),2, 3, 10, 12, 60),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Glute Ham Raise'),3, 3, 6, 10, 90),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Frog Pumps'),4, 3, 12, 15, 45),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 6, 8, 120),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),1, 4, 6, 8, 120),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Press Militar (Military Press)'),2, 3, 8, 10, 90),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),3, 3, 8, 12, 90),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Push Down com Corda'),4, 3, 10, 12, 60),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Rosca com Halteres'),5, 3, 10, 12, 60),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Levantamento Morto Romeno'),1, 4, 6, 8, 120),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Leg Press'),2, 3, 8, 12, 90),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Flexão de Perna'),3, 3, 10, 12, 60),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Extensão de Perna'),4, 3, 10, 12, 60),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Elevação de Gémeos Sentado'),5, 4, 12, 15, 45),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 6, 8, 120),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Supino Inclinado'),1, 3, 8, 10, 90),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Press Militar (Military Press)'),2, 3, 8, 10, 90),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Elevação Lateral'),3, 3, 12, 15, 60),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Push Down com Corda'),4, 3, 10, 12, 60),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Extensão no Cabo com Corda'),5, 3, 10, 12, 60),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Deadlift com Trap Bar'),0, 3, 3, 5, 180),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Puxada V'),1, 3, 8, 12, 90),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Remada T-Bar'),2, 3, 8, 12, 90),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Reverse Fly (Máquina)'),3, 3, 12, 15, 60),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Rosca EZ'),4, 3, 8, 12, 60),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Rosca Martelo'),5, 3, 10, 12, 60),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Belt Squat'),1, 3, 8, 12, 120),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Levantamento Morto Romeno'),2, 3, 6, 8, 120),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Flexão de Perna'),3, 3, 10, 12, 60),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Extensão de Perna'),4, 3, 10, 12, 60),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Elevação de Gémeos em Pé'),5, 4, 10, 15, 45),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 5, 5, 5, 180),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Supino (Barbell)'),1, 5, 5, 5, 180),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),2, 5, 5, 5, 180),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Press Militar (Military Press)'),3, 5, 5, 5, 150),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 8, 12, 90),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Supino Inclinado com Halteres'),1, 3, 10, 12, 75),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Remada Apoiada no Peito'),2, 3, 10, 12, 75),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),3, 3, 10, 12, 75),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Elevação Lateral no Cabo'),4, 3, 12, 15, 60),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Rosca Inclinado com Halteres'),5, 3, 10, 12, 60),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Push Down com Corda'),6, 3, 10, 12, 60),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Burpees'),0, 6, 20, 30, 30),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Battle Ropes'),1, 6, 30, 40, 30),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Corda de Pular'),2, 6, 30, 45, 30),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Sprints'),3, 6, 20, 30, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Prancha (Plank)'),0, 3, 30, 45, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Prancha Lateral'),1, 3, 20, 30, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Dead Bug'),2, 3, 10, 12, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Pallof Press'),3, 3, 12, 15, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Russian Twist'),4, 3, 12, 15, 30),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Hip Thrust'),0, 4, 8, 12, 90),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Agachamento (Back Squat)'),1, 3, 6, 8, 120),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Abdução no Cabo'),2, 3, 12, 15, 45),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Chute Traseiro (Cable)'),3, 3, 12, 15, 45),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Frog Pumps'),4, 3, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Gémeos em Pé'),0, 4, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Gémeos Sentado'),1, 4, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Gémeos Donkey'),2, 3, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Crunch Reverso'),3, 3, 12, 15, 30),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Joelhos Suspensa'),4, 3, 10, 12, 30),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Supino no Chão'),0, 4, 5, 6, 120),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Landmine Press'),1, 3, 6, 8, 90),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Remada T-Bar'),2, 4, 6, 8, 120),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Puxada Neutra'),3, 3, 8, 10, 90),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Cuban Press'),4, 2, 10, 12, 60),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Deadlift com Trap Bar'),0, 3, 3, 5, 180),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Thrusters'),1, 3, 8, 10, 90),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Kettlebell Swing'),2, 3, 12, 15, 60),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Empurrão de Trenó'),3, 4, 20, 30, 60),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Hollow Hold'),4, 3, 20, 30, 30);

commit;
