-- Seed definitivo (generated from src/shared/data/exercises.ts)
begin;

-- Remove existing base template plans and their exercises
delete from plan_exercises where plan_id in (select id from workout_plans where is_template = true);
delete from workout_plans where is_template = true;

-- Remove global (non-custom) exercises
delete from exercises where is_custom = false;

insert into exercises (id, name, name_pt, muscle_groups, secondary_muscles, equipment, difficulty, instructions, tips, gif_url, video_url, is_custom, created_by, is_premium)
values
(gen_random_uuid(), 'Supino (Barbell)', 'Supino (Barbell)', '{Peito, Tríceps}', '{}', '{barbell, banco}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino Inclinado', 'Supino Inclinado', '{Peito, Tríceps, Ombro}', '{}', '{barbell, banco}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino com Halteres', 'Supino com Halteres', '{Peito, Tríceps}', '{}', '{dumbbell, banco}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Pec Deck / Fly (Cable)', 'Pec Deck / Fly (Cable)', '{Peito}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Dumbbell Fly', 'Dumbbell Fly', '{Peito}', '{}', '{dumbbell, banco}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino Declinado', 'Supino Declinado', '{Peito, Tríceps}', '{}', '{barbell, banco}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino Inclinado com Halteres', 'Supino Inclinado com Halteres', '{Peito, Tríceps, Ombro}', '{}', '{dumbbell, banco}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Chest Press (Máquina)', 'Chest Press (Máquina)', '{Peito, Tríceps}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Crossover no Cabo', 'Crossover no Cabo', '{Peito}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Mergulho para Peito', 'Mergulho para Peito', '{Peito, Tríceps}', '{}', '{dip_station}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino no Smith', 'Supino no Smith', '{Peito, Tríceps}', '{}', '{smith_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino no Chão', 'Supino no Chão', '{Peito, Tríceps}', '{}', '{barbell, dumbbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Landmine Press', 'Landmine Press', '{Peito, Ombro, Tríceps}', '{}', '{barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexões (Push-ups)', 'Flexões (Push-ups)', '{Peito, Tríceps}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Supino', 'Máquina de Supino', '{Peito}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Fly com Banda Elástica', 'Fly com Banda Elástica', '{Peito}', '{}', '{resistance_band}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Levantamento Morto (Deadlift)', 'Levantamento Morto (Deadlift)', '{Costas, Pernas, Glúteos}', '{}', '{barbell}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Linha Inclinada (Bent Row)', 'Linha Inclinada (Bent Row)', '{Costas, Bíceps}', '{}', '{barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Linha com Halteres', 'Linha com Halteres', '{Costas, Bíceps}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Dominadas (Pull-ups)', 'Dominadas (Pull-ups)', '{Costas, Bíceps}', '{}', '{pull_up_bar}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Puxada Frontal (Lat Pulldown)', 'Puxada Frontal (Lat Pulldown)', '{Costas, Bíceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Dominadas Assistidas', 'Dominadas Assistidas', '{Costas, Bíceps}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Face Pull', 'Face Pull', '{Costas, Ombro}', '{}', '{cable_machine, rope}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Linha', 'Máquina de Linha', '{Costas}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Linha por Cabo', 'Linha por Cabo', '{Costas, Bíceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Seal Row', 'Seal Row', '{Costas}', '{}', '{barbell, bench}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Remada T-Bar', 'Remada T-Bar', '{Costas, Bíceps}', '{}', '{barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Remada Apoiada no Peito', 'Remada Apoiada no Peito', '{Costas, Bíceps}', '{}', '{dumbbell, bench}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Remada Unilateral no Cabo', 'Remada Unilateral no Cabo', '{Costas, Bíceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Pulldown com Braço Estendido', 'Pulldown com Braço Estendido', '{Costas}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Pullover', 'Pullover', '{Costas, Peito}', '{}', '{dumbbell, cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Remada Invertida', 'Remada Invertida', '{Costas, Bíceps}', '{}', '{barbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Deadlift com Trap Bar', 'Deadlift com Trap Bar', '{Pernas, Costas, Glúteos}', '{}', '{trap_bar}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Puxada Neutra', 'Puxada Neutra', '{Costas, Bíceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Puxada V', 'Puxada V', '{Costas, Bíceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Meadows Row', 'Meadows Row', '{Costas}', '{}', '{barbell}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Reverse Fly (Máquina)', 'Reverse Fly (Máquina)', '{Costas, Ombro}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Extensão Lombar', 'Extensão Lombar', '{Costas}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Press Militar (Military Press)', 'Press Militar (Military Press)', '{Ombro, Tríceps}', '{}', '{barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Desenvolvimento de Ombro', 'Desenvolvimento de Ombro', '{Ombro, Tríceps}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação Lateral', 'Elevação Lateral', '{Ombro}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação Frontal', 'Elevação Frontal', '{Ombro}', '{}', '{dumbbell, barbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Fly Posterior', 'Fly Posterior', '{Ombro}', '{}', '{dumbbell, machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Ombro', 'Máquina de Ombro', '{Ombro}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Linha Alta (Upright Row)', 'Linha Alta (Upright Row)', '{Ombro, Bíceps}', '{}', '{barbell, dumbbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Encolhimento de Ombros (Shrug)', 'Encolhimento de Ombros (Shrug)', '{Ombro}', '{}', '{barbell, dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Arnold Press', 'Arnold Press', '{Ombro, Tríceps}', '{}', '{dumbbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação Lateral no Cabo', 'Elevação Lateral no Cabo', '{Ombro}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Posterior no Cabo', 'Posterior no Cabo', '{Ombro}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Cuban Press', 'Cuban Press', '{Ombro}', '{}', '{dumbbell}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação Y', 'Elevação Y', '{Ombro}', '{}', '{dumbbell, cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Barbell', 'Rosca Barbell', '{Bíceps}', '{}', '{barbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca com Halteres', 'Rosca com Halteres', '{Bíceps}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca por Cabo', 'Rosca por Cabo', '{Bíceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Martelo', 'Rosca Martelo', '{Bíceps, Antebraço}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Barbell Inclinada', 'Rosca Barbell Inclinada', '{Bíceps}', '{}', '{barbell, bench}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Rosca', 'Máquina de Rosca', '{Bíceps}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca de Concentração', 'Rosca de Concentração', '{Bíceps}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Inclinado com Halteres', 'Rosca Inclinado com Halteres', '{Bíceps}', '{}', '{dumbbell, bench}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Spider', 'Rosca Spider', '{Bíceps}', '{}', '{barbell, bench}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca EZ', 'Rosca EZ', '{Bíceps}', '{}', '{barbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Reversa', 'Rosca Reversa', '{Bíceps, Antebraço}', '{}', '{barbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Rosca Martelo no Cabo', 'Rosca Martelo no Cabo', '{Bíceps, Antebraço}', '{}', '{cable_machine, rope}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Mergulho de Tríceps', 'Mergulho de Tríceps', '{Tríceps, Peito}', '{}', '{dip_station}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Extensão de Tríceps (Overhead)', 'Extensão de Tríceps (Overhead)', '{Tríceps}', '{}', '{dumbbell, barbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Push Down com Corda', 'Push Down com Corda', '{Tríceps}', '{}', '{cable_machine, rope}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Push Down de Tríceps', 'Push Down de Tríceps', '{Tríceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Extensão Aérea', 'Extensão Aérea', '{Tríceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Skull Crusher', 'Skull Crusher', '{Tríceps}', '{}', '{barbell, dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Tríceps', 'Máquina de Tríceps', '{Tríceps}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Supino com Grip Fechado', 'Supino com Grip Fechado', '{Tríceps, Peito}', '{}', '{barbell, banco}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Dips no Banco', 'Dips no Banco', '{Tríceps}', '{}', '{bench}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Extensão no Cabo com Corda', 'Extensão no Cabo com Corda', '{Tríceps}', '{}', '{cable_machine, rope}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexões Diamante', 'Flexões Diamante', '{Tríceps, Peito}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Pushdown Unilateral', 'Pushdown Unilateral', '{Tríceps}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Dip Assistido', 'Dip Assistido', '{Tríceps, Peito}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexão de Pulso', 'Flexão de Pulso', '{Antebraço}', '{}', '{barbell, dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexão Reversa de Pulso', 'Flexão Reversa de Pulso', '{Antebraço}', '{}', '{barbell, dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Andar do Fazendeiro', 'Andar do Fazendeiro', '{Antebraço, Grip}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Wrist Roller', 'Wrist Roller', '{Antebraço}', '{}', '{other}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento (Back Squat)', 'Agachamento (Back Squat)', '{Pernas, Glúteos}', '{}', '{barbell, rack}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento Frontal', 'Agachamento Frontal', '{Pernas, Glúteos}', '{}', '{barbell, rack}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento com Halter', 'Agachamento com Halter', '{Pernas, Glúteos}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Leg Press', 'Leg Press', '{Pernas, Glúteos}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Hack Squat', 'Hack Squat', '{Pernas, Glúteos}', '{}', '{machine}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento Smith', 'Agachamento Smith', '{Pernas, Glúteos}', '{}', '{smith_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Extensão de Perna', 'Extensão de Perna', '{Quadríceps}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Sissy Squat', 'Sissy Squat', '{Quadríceps}', '{}', '{}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento Búlgaro', 'Agachamento Búlgaro', '{Pernas, Glúteos}', '{}', '{dumbbell, bench}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Avanço (Lunges)', 'Avanço (Lunges)', '{Pernas, Glúteos}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Step-Up', 'Step-Up', '{Pernas, Glúteos}', '{}', '{bench, dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Leg Press Horizontal', 'Leg Press Horizontal', '{Pernas, Glúteos}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Belt Squat', 'Belt Squat', '{Pernas, Glúteos}', '{}', '{machine}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento ao Banco', 'Agachamento ao Banco', '{Pernas, Glúteos}', '{}', '{barbell, box}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexão de Perna', 'Flexão de Perna', '{Femorais}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexão de Perna Deitado', 'Flexão de Perna Deitado', '{Femorais}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Nordic Curl', 'Nordic Curl', '{Femorais}', '{}', '{}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Glute Ham Raise', 'Glute Ham Raise', '{Femorais, Glúteos}', '{}', '{machine}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Levantamento Morto Romeno', 'Levantamento Morto Romeno', '{Femorais, Glúteos, Costas}', '{}', '{barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Levantamento Morto Rígido', 'Levantamento Morto Rígido', '{Femorais, Costas}', '{}', '{barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexão de Perna Sentado', 'Flexão de Perna Sentado', '{Femorais}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Good Morning', 'Good Morning', '{Femorais, Glúteos, Costas}', '{}', '{barbell}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'RDL Unilateral', 'RDL Unilateral', '{Femorais, Glúteos}', '{}', '{dumbbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Deadlift com Kettlebell', 'Deadlift com Kettlebell', '{Femorais, Glúteos}', '{}', '{kettlebell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Hip Thrust', 'Hip Thrust', '{Glúteos, Pernas}', '{}', '{barbell, bench}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Ponte de Glúteos', 'Ponte de Glúteos', '{Glúteos}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Chute Traseiro (Cable)', 'Chute Traseiro (Cable)', '{Glúteos}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina Adutora', 'Máquina Adutora', '{Glúteos, Pernas}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina Abdutora', 'Máquina Abdutora', '{Glúteos}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Agachamento Pêndulo', 'Agachamento Pêndulo', '{Glúteos, Pernas}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Abdução com Banda', 'Abdução com Banda', '{Glúteos}', '{}', '{resistance_band}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Abdução no Cabo', 'Abdução no Cabo', '{Glúteos}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Frog Pumps', 'Frog Pumps', '{Glúteos}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Abdominais (Crunch)', 'Abdominais (Crunch)', '{Abdominais}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Ab Wheel', 'Ab Wheel', '{Abdominais, Core}', '{}', '{ab_wheel}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Abdominais por Cabo', 'Abdominais por Cabo', '{Abdominais}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Movimento de Lenhador', 'Movimento de Lenhador', '{Abdominais, Oblíquos}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação de Perna Suspensa', 'Elevação de Perna Suspensa', '{Abdominais}', '{}', '{pull_up_bar}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Abdominais', 'Máquina de Abdominais', '{Abdominais}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Prancha (Plank)', 'Prancha (Plank)', '{Abdominais, Core}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Dead Bug', 'Dead Bug', '{Abdominais, Core}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Pallof Press', 'Pallof Press', '{Oblíquos, Core}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Russian Twist', 'Russian Twist', '{Oblíquos, Core}', '{}', '{dumbbell}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Prancha Lateral', 'Prancha Lateral', '{Oblíquos, Core}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação de Joelhos Suspensa', 'Elevação de Joelhos Suspensa', '{Abdominais}', '{}', '{pull_up_bar}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Crunch Reverso', 'Crunch Reverso', '{Abdominais}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Hollow Hold', 'Hollow Hold', '{Core, Abdominais}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Flexão Lateral no Cabo', 'Flexão Lateral no Cabo', '{Oblíquos}', '{}', '{cable_machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Esteira (Treadmill)', 'Esteira (Treadmill)', '{}', '{}', '{treadmill}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Bicicleta Estática', 'Bicicleta Estática', '{Pernas}', '{}', '{stationary_bike}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Máquina de Remo', 'Máquina de Remo', '{Costas, Pernas}', '{}', '{rowing_machine}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elíptica', 'Elíptica', '{Pernas}', '{}', '{elliptical}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Corda de Pular', 'Corda de Pular', '{Pernas, Braços}', '{}', '{jump_rope}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Battle Ropes', 'Battle Ropes', '{Braços, Core}', '{}', '{battle_ropes}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Burpees', 'Burpees', '{}', '{}', '{}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Salto para Caixa', 'Salto para Caixa', '{Pernas}', '{}', '{plyo_box}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Sprints', 'Sprints', '{Pernas}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Escadas (Stair Climber)', 'Escadas (Stair Climber)', '{Pernas}', '{}', '{stair_climber}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Air Bike', 'Air Bike', '{Pernas, Braços}', '{}', '{assault_bike}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'SkiErg', 'SkiErg', '{Costas, Braços}', '{}', '{skierg}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Kettlebell Swing', 'Kettlebell Swing', '{Glúteos, Pernas, Core}', '{}', '{kettlebell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Tire Flip', 'Tire Flip', '{Pernas, Costas}', '{}', '{tire}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Empurrão de Trenó', 'Empurrão de Trenó', '{Pernas}', '{}', '{sled}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Arrasto de Trenó', 'Arrasto de Trenó', '{Pernas}', '{}', '{sled}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Power Clean', 'Power Clean', '{Pernas, Costas, Ombro}', '{}', '{barbell}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Thrusters', 'Thrusters', '{Pernas, Ombro, Braços}', '{}', '{dumbbell, barbell}', 3, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Turkish Get-up', 'Turkish Get-up', '{Core, Ombro}', '{}', '{kettlebell}', 5, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação de Gémeos em Pé', 'Elevação de Gémeos em Pé', '{Panturrilha}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação de Gémeos Sentado', 'Elevação de Gémeos Sentado', '{Panturrilha}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação de Gémeos Donkey', 'Elevação de Gémeos Donkey', '{Panturrilha}', '{}', '{machine}', 1, NULL, NULL, NULL, NULL, false, NULL, false),
(gen_random_uuid(), 'Elevação de Gémeos Unilateral', 'Elevação de Gémeos Unilateral', '{Panturrilha}', '{}', '{}', 1, NULL, NULL, NULL, NULL, false, NULL, false);

-- Base template plans with exercises
with ex as (select id, name from exercises)
insert into workout_plans (user_id, name, description, type, days_per_week, estimated_duration_min, is_template, is_public) values
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Full Body (Iniciante)', 'Sessão completa para iniciantes, foco em técnica e compostos básicos.', 'full_body', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Full Body (Intermédio)', 'Treino completo com mais volume e compostos.', 'full_body', 3, 70, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Push (Peito/Tríceps)', 'Peito e tríceps com foco em força e hipertrofia.', 'chest_triceps', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Pull (Costas/Bíceps)', 'Costas e bíceps com remadas e puxadas.', 'back_biceps', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Legs (Quadríceps)', 'Foco em quadríceps e agachamentos.', 'legs_quad', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Posterior & Glúteos', 'Femorais e glúteos com hinge pesado.', 'legs_posterior', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Upper (Intermédio)', 'Treino de trem superior equilibrado.', 'upper', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Lower (Intermédio)', 'Treino de trem inferior equilibrado.', 'lower', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'PPL - Push', 'Push day clássico para PPL.', 'push', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'PPL - Pull', 'Pull day clássico para PPL.', 'pull', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'PPL - Legs', 'Leg day clássico para PPL.', 'legs_quad', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Strength 5x5', 'Plano base de força com 5x5 nos principais levantamentos.', 'full_body', 3, 70, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Hipertrofia Upper', 'Volume extra para membros superiores.', 'upper', 4, 70, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Condicionamento HIIT', 'Sessão rápida de cardio intenso.', 'cardio_hiit', 2, 30, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Core & Mobility', 'Core, estabilidade e mobilidade.', 'core', 2, 35, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Glúteos Intensivo', 'Foco em glúteos e posterior.', 'legs_posterior', 2, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Panturrilhas & Core', 'Panturrilha + core para estabilidade.', 'core', 2, 35, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Power Upper', 'Força e potência no trem superior.', 'upper', 3, 60, true, true),
('f3c008f8-4d2c-47e4-a00e-0836b95569f1', 'Athletic Performance', 'Potência, core e condicionamento geral.', 'full_body', 3, 60, true, true) returning id, name;

-- Link exercises to templates
with p as (select id, name from workout_plans where is_template = true), ex as (select id, name from exercises)
insert into plan_exercises (plan_id, exercise_id, order_index, sets, reps_min, reps_max, rest_seconds) values
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Agachamento com Halter'),0, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Supino com Halteres'),1, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),2, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Linha com Halteres'),3, 3, 10, 12, 90),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Desenvolvimento de Ombro'),4, 2, 10, 12, 60),
((select id from p where name = 'Full Body (Iniciante)'),(select id from ex where name = 'Prancha (Plank)'),5, 3, 30, 45, 45),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Supino (Barbell)'),1, 4, 6, 8, 120),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),2, 4, 6, 8, 120),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Press Militar (Military Press)'),3, 3, 8, 10, 90),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),4, 3, 8, 12, 90),
((select id from p where name = 'Full Body (Intermédio)'),(select id from ex where name = 'Pallof Press'),5, 3, 12, 15, 45),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 6, 8, 120),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino Inclinado'),1, 3, 8, 10, 90),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino Inclinado com Halteres'),2, 3, 8, 12, 90),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Crossover no Cabo'),3, 3, 10, 12, 60),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Push Down com Corda'),4, 3, 10, 12, 60),
((select id from p where name = 'Push (Peito/Tríceps)'),(select id from ex where name = 'Supino com Grip Fechado'),5, 3, 6, 8, 90),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),0, 4, 6, 8, 120),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Puxada Neutra'),1, 3, 8, 12, 90),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Remada T-Bar'),2, 3, 8, 12, 90),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Face Pull'),3, 3, 12, 15, 60),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Rosca EZ'),4, 3, 8, 12, 60),
((select id from p where name = 'Pull (Costas/Bíceps)'),(select id from ex where name = 'Rosca Martelo'),5, 3, 10, 12, 60),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Belt Squat'),1, 4, 8, 12, 120),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Leg Press'),2, 3, 8, 12, 90),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Agachamento Búlgaro'),3, 3, 8, 10, 90),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Extensão de Perna'),4, 3, 10, 12, 60),
((select id from p where name = 'Legs (Quadríceps)'),(select id from ex where name = 'Elevação de Gémeos em Pé'),5, 4, 10, 15, 45),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Levantamento Morto Romeno'),0, 4, 6, 8, 120),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Hip Thrust'),1, 4, 8, 10, 90),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Flexão de Perna'),2, 3, 10, 12, 60),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Glute Ham Raise'),3, 3, 6, 10, 90),
((select id from p where name = 'Posterior & Glúteos'),(select id from ex where name = 'Frog Pumps'),4, 3, 12, 15, 45),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 6, 8, 120),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),1, 4, 6, 8, 120),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Press Militar (Military Press)'),2, 3, 8, 10, 90),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),3, 3, 8, 12, 90),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Push Down com Corda'),4, 3, 10, 12, 60),
((select id from p where name = 'Upper (Intermédio)'),(select id from ex where name = 'Rosca com Halteres'),5, 3, 10, 12, 60),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Levantamento Morto Romeno'),1, 4, 6, 8, 120),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Leg Press'),2, 3, 8, 12, 90),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Flexão de Perna'),3, 3, 10, 12, 60),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Extensão de Perna'),4, 3, 10, 12, 60),
((select id from p where name = 'Lower (Intermédio)'),(select id from ex where name = 'Elevação de Gémeos Sentado'),5, 4, 12, 15, 45),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 6, 8, 120),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Supino Inclinado'),1, 3, 8, 10, 90),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Press Militar (Military Press)'),2, 3, 8, 10, 90),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Elevação Lateral'),3, 3, 12, 15, 60),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Push Down com Corda'),4, 3, 10, 12, 60),
((select id from p where name = 'PPL - Push'),(select id from ex where name = 'Extensão no Cabo com Corda'),5, 3, 10, 12, 60),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Deadlift com Trap Bar'),0, 3, 3, 5, 180),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Puxada V'),1, 3, 8, 12, 90),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Remada T-Bar'),2, 3, 8, 12, 90),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Reverse Fly (Máquina)'),3, 3, 12, 15, 60),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Rosca EZ'),4, 3, 8, 12, 60),
((select id from p where name = 'PPL - Pull'),(select id from ex where name = 'Rosca Martelo'),5, 3, 10, 12, 60),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 4, 5, 8, 120),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Belt Squat'),1, 3, 8, 12, 120),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Levantamento Morto Romeno'),2, 3, 6, 8, 120),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Flexão de Perna'),3, 3, 10, 12, 60),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Extensão de Perna'),4, 3, 10, 12, 60),
((select id from p where name = 'PPL - Legs'),(select id from ex where name = 'Elevação de Gémeos em Pé'),5, 4, 10, 15, 45),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Agachamento (Back Squat)'),0, 5, 5, 5, 180),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Supino (Barbell)'),1, 5, 5, 5, 180),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Linha Inclinada (Bent Row)'),2, 5, 5, 5, 180),
((select id from p where name = 'Strength 5x5'),(select id from ex where name = 'Press Militar (Military Press)'),3, 5, 5, 5, 150),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Supino (Barbell)'),0, 4, 8, 12, 90),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Supino Inclinado com Halteres'),1, 3, 10, 12, 75),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Remada Apoiada no Peito'),2, 3, 10, 12, 75),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Puxada Frontal (Lat Pulldown)'),3, 3, 10, 12, 75),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Elevação Lateral no Cabo'),4, 3, 12, 15, 60),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Rosca Inclinado com Halteres'),5, 3, 10, 12, 60),
((select id from p where name = 'Hipertrofia Upper'),(select id from ex where name = 'Push Down com Corda'),6, 3, 10, 12, 60),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Burpees'),0, 6, 20, 30, 30),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Battle Ropes'),1, 6, 30, 40, 30),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Corda de Pular'),2, 6, 30, 45, 30),
((select id from p where name = 'Condicionamento HIIT'),(select id from ex where name = 'Sprints'),3, 6, 20, 30, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Prancha (Plank)'),0, 3, 30, 45, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Prancha Lateral'),1, 3, 20, 30, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Dead Bug'),2, 3, 10, 12, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Pallof Press'),3, 3, 12, 15, 30),
((select id from p where name = 'Core & Mobility'),(select id from ex where name = 'Russian Twist'),4, 3, 12, 15, 30),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Hip Thrust'),0, 4, 8, 12, 90),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Agachamento (Back Squat)'),1, 3, 6, 8, 120),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Abdução no Cabo'),2, 3, 12, 15, 45),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Chute Traseiro (Cable)'),3, 3, 12, 15, 45),
((select id from p where name = 'Glúteos Intensivo'),(select id from ex where name = 'Frog Pumps'),4, 3, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Gémeos em Pé'),0, 4, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Gémeos Sentado'),1, 4, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Gémeos Donkey'),2, 3, 12, 15, 45),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Crunch Reverso'),3, 3, 12, 15, 30),
((select id from p where name = 'Panturrilhas & Core'),(select id from ex where name = 'Elevação de Joelhos Suspensa'),4, 3, 10, 12, 30),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Supino no Chão'),0, 4, 5, 6, 120),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Landmine Press'),1, 3, 6, 8, 90),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Remada T-Bar'),2, 4, 6, 8, 120),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Puxada Neutra'),3, 3, 8, 10, 90),
((select id from p where name = 'Power Upper'),(select id from ex where name = 'Cuban Press'),4, 2, 10, 12, 60),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Deadlift com Trap Bar'),0, 3, 3, 5, 180),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Thrusters'),1, 3, 8, 10, 90),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Kettlebell Swing'),2, 3, 12, 15, 60),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Empurrão de Trenó'),3, 4, 20, 30, 60),
((select id from p where name = 'Athletic Performance'),(select id from ex where name = 'Hollow Hold'),4, 3, 20, 30, 30);

commit;
